dist: bionic
sudo: required
language:
  - cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - clang-7
before_install:
  - sudo apt-get install -y libgtest-dev libeigen3-dev libgoogle-glog-dev cmake build-essential
script: make && ./bin/tracker_unit_tests
